name: CI - ABOA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Frontend React
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ABOA - lllSEM/aboa-react

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Rodar build
        run: npm run build

  backend:
    name: Backend Node
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ABOA - lllSEM/backend

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Instalar dependências
        run: npm install

      - name: Checar sintaxe
        run: |
          node --check server.js
          node --check routes/estabelecimentoRoutes.js
          node --check routes/authRoutes.js
          node --check routes/cardapioRoutes.js
